
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tocaform?schema=tocadev
    name: tocadev
    username: tocadev
    password: tocadev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: false

security:
  oauth2:
    client:
      client-id: webtoca
      client-secret: webtoca

jwt:
  secret: MY-JWT-SECRET
  duration: 86400
server:
  port: ${PORT:8080}


