spring:
  datasource:
    name: tocadb
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true

security:
  oauth2:
    client:
      client-id: webtoca
      client-secret: webtoca

jwt:
  secret: MY-JWT-SECRET
  duration: 86400



